export const INPUT_VALUE_CHANGE = "INPUT_VALUE_CHANGE";
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const INIT_TODO_LIST = "INIT_TODO_LIST";